"""Node [13] - refusal composer (architecture.md section 5.13, PRD FR5).

Every refusal in this product is assembled here, from a template and a curated
link. No refusal text is ever generated by a model, and that is the whole point
(PRD G3 = 100% refusal correctness): a refusal is the one response where being
wrong is unacceptable and being fluent buys nothing. Templates also make the
boundaries unfakeable - there is no prompt through which a model could be talked
into quoting a return figure, because no model is in this path.

Two content rules from FR5 are enforced structurally rather than by review:

* a refusal never restates the question, so the user's own words cannot be
  echoed back as if they were an assertion the assistant had accepted;
* a refusal never moralizes, so there is no scolding about suitability.

The link for each class comes from ``config/educational_links.yaml``, where
every URL carries the status code it returned when it was verified.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from ..common.errors import ConfigError
from ..common.models import REFUSAL_CLASSES, RefusalResponse

_FOOTER = "Facts-only. No investment advice."


def _without_trailing_footer(text: str) -> str:
    """Drop a trailing facts-only line so the composer can add exactly one.

    The scope note is a local asset that happens to end with the same sentence
    the composer appends. Normalizing it here keeps "every refusal ends with
    exactly one footer" true without the composer having to know where the note
    came from.
    """
    lines = text.strip().splitlines()
    while lines and not lines[-1].strip():
        lines.pop()
    if lines and lines[-1].strip() == _FOOTER:
        lines.pop()
    return "\n".join(lines).strip()

# {boundary}: the one sentence that names what will not be answered.
# {redirect}: the optional sentence pointing at what can be.
_TEMPLATES: dict[str, tuple[str, str]] = {
    "pii": (
        "I cannot use a query that contains personal identifiers, so I have "
        "discarded it without reading or storing it.",
        "You can ask the same question again with the identifier removed.",
    ),
    "opinionated": (
        "I do not give investment recommendations or tell you whether a fund is "
        "good, safe, or worth buying.",
        "I can tell you the documented facts of these five schemes, such as "
        "expense ratio, exit load, minimum investment, riskometer level and "
        "benchmark.",
    ),
    "portfolio_personal": (
        "I do not advise on how much to invest or how to allocate your money.",
        "I can read you the documented facts of any of these five schemes so you "
        "can work through the decision yourself.",
    ),
    "performance": (
        "I do not quote returns, CAGR or any other performance figure.",
        "The published performance figures for the scheme are on its official "
        "page, linked below.",
    ),
    "out_of_scope": (
        "I only cover five HDFC mutual fund schemes, and this question is not "
        "about them.",
        "The schemes I cover are listed below.",
    ),
    "grounding_fail": (
        "I could not find that in the official documents I am built on, so I "
        "will not answer from memory.",
        "The official page for the scheme is linked below; the figure you want "
        "should be there.",
    ),
}


@dataclass(frozen=True, slots=True)
class RefusalComposer:
    """Builds a templated refusal with at most one curated link."""

    links: dict[str, Any]
    scheme_urls: dict[str, str]
    scheme_names: dict[str, str] = field(default_factory=dict)
    local_note: str = ""

    @classmethod
    def load(
        cls,
        links_path: str | Path,
        scheme_urls: dict[str, str],
        scheme_names: dict[str, str] | None = None,
        local_note: str = "",
    ) -> RefusalComposer:
        path = Path(links_path)
        if not path.is_file():
            raise ConfigError(f"educational link registry not found: {path}")
        try:
            raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError as exc:
            raise ConfigError(f"{path}: invalid YAML: {exc}") from exc
        if not isinstance(raw, dict) or not isinstance(raw.get("classes"), dict):
            raise ConfigError(f"{path}: expected a 'classes' mapping")

        classes = raw["classes"]
        missing = [c for c in REFUSAL_CLASSES if c not in classes]
        if missing:
            raise ConfigError(f"{path}: no link entry for refusal class(es) {missing}")

        for name, entry in classes.items():
            if not isinstance(entry, dict):
                raise ConfigError(f"{path}: classes.{name} must be a mapping")
            # Provenance keys are carried alongside the link so the substitution
            # reasoning travels with the URL instead of living in a commit message.
            allowed = {
                "intent",
                "link",
                "link_from_registry",
                "fallback_link",
                "note",
                "substitution_note",
                "gap_note",
                "fallback_reason",
                "preferred_when_available",
                "local_note",
                "registry_field",
            }
            unknown = sorted(set(entry) - allowed)
            if unknown:
                raise ConfigError(f"{path}: classes.{name}: unknown key(s) {unknown}")

        return cls(
            links=classes,
            scheme_urls=dict(scheme_urls),
            scheme_names=dict(scheme_names or {}),
            local_note=local_note,
        )

    def compose(
        self,
        query_class: str,
        scheme_key: str | None = None,
        rule_id: str = "",
        multi_scheme: bool = False,
    ) -> RefusalResponse:
        if query_class not in _TEMPLATES:
            raise ConfigError(f"no refusal template for class {query_class!r}")

        boundary, redirect = _TEMPLATES[query_class]
        label, url = self._link_for(query_class, scheme_key)
        if multi_scheme and label:
            # D4 allows exactly one link, so a question naming two schemes cannot
            # be given both pages. Say which one was linked instead of implying
            # the single link covers everything the user asked about.
            redirect = f"{redirect} One of the schemes you named is linked below."
        elif url == self._fallback_url(query_class) and query_class in (
            "performance",
            "grounding_fail",
        ):
            # No scheme resolved, so there is no scheme-specific page to point at.
            # Asking for the scheme is the useful next step, not a generic link.
            redirect = f"{redirect} Name the scheme and I can point you at its own page."

        lines = [boundary, redirect]
        # The scope note carries the list of covered schemes, which FR3 requires
        # in the out_of_scope response itself - the external link is a supplement
        # to that list, never a replacement for it.
        if self.local_note and query_class == "out_of_scope":
            lines.append(_without_trailing_footer(self.local_note))
        if label and url:
            lines.append(f"Educational link: {label} - {url}")
        # Appended unconditionally so the invariant is "every refusal ends with
        # exactly one facts-only line". The note is normalized above rather than
        # checked here: assets/scope_note.txt ends with the same sentence, and an
        # append that inspected only the last line missed it because the
        # educational link lands in between. That printed the footer twice in the
        # out_of_scope refusal, which a user reads verbatim in the P5 thread.
        lines.append(_FOOTER)
        return RefusalResponse(
            query_class=query_class,
            text="\n".join(lines),
            link_label=label,
            link_url=url,
            rule_id=rule_id,
        )

    def _fallback_url(self, query_class: str) -> str:
        entry = self.links.get(query_class, {}) or {}
        return str((entry.get("fallback_link") or {}).get("url", ""))

    def _link_for(self, query_class: str, scheme_key: str | None) -> tuple[str, str]:
        entry = self.links.get(query_class, {}) or {}
        if entry.get("link_from_registry"):
            if not scheme_key:
                fallback = entry.get("fallback_link") or {}
                return str(fallback.get("label", "")), str(fallback.get("url", ""))
            url = self.scheme_urls.get(scheme_key, "")
            if not url:
                fallback = entry.get("fallback_link") or {}
                return str(fallback.get("label", "")), str(fallback.get("url", ""))
            name = self.scheme_names.get(scheme_key, scheme_key)
            return f"{name} - official scheme page", url
        link = entry.get("link") or {}
        return str(link.get("label", "")), str(link.get("url", ""))
