"""Generate artifacts/sample_qa.md from real pipeline responses (P6-T3).

Every answer below is the verbatim ``AskResponse.text`` the live pipeline
returned - citation and stamp included, because ask.py attaches both from chunk
metadata. Nothing in the output is written by hand; re-run to regenerate.

The PII sample is sent with a PAN-shaped value, as a user would type it, but the
question is recorded through ``common.redaction.redact`` so no PII-shaped string
is ever written to disk (PRD FR6, tests/test_no_pii_at_rest.py).

    python scripts/make_sample_qa.py [--pace-s 7]
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import pathlib
import sys
import time

from mf_facts.common.config import load_config
from mf_facts.common.errors import LLMError
from mf_facts.common.redaction import redact
from mf_facts.online.ask import AnswerPipeline

ROOT = pathlib.Path(__file__).resolve().parents[1]

#: (what the entry demonstrates, question). Covers the six PRD 5.2 / 9.1 fact
#: categories, one how-to, and the refusal classes a reviewer will probe.
SAMPLES: list[tuple[str, str]] = [
    ("Fact: expense ratio", "What is the expense ratio of HDFC Small Cap Fund?"),
    ("Fact: exit load (UI example 1)", "What is the exit load on HDFC Large Cap Fund?"),
    ("Fact: minimum SIP", "What is the minimum SIP amount for HDFC Balanced Advantage Fund?"),
    ("Fact: ELSS lock-in (UI example 2)", "Is there a lock-in period on the HDFC ELSS Tax Saver Fund?"),
    ("Fact: riskometer / benchmark", "What is the riskometer rating and benchmark of HDFC Flexi Cap Fund?"),
    ("Fact: statement download (UI example 3)", "How do I download my capital gains statement?"),
    ("How-to", "How long must I hold HDFC Large Cap Fund before the exit load does not apply?"),
    ("Refusal: opinionated", "Should I invest in HDFC Small Cap Fund?"),
    ("Refusal: performance", "What are the 3 year returns of HDFC ELSS Tax Saver Fund?"),
    ("Refusal: PII", "My PAN is ABCDE1234F, what is the expense ratio of HDFC Large Cap Fund?"),
]


def _ask(pipeline: AnswerPipeline, question: str, pace_s: float):
    for attempt in range(7):
        try:
            return pipeline.ask(question)
        except LLMError as exc:
            if "HTTP 429" not in str(exc) or attempt == 6:
                raise
            time.sleep(pace_s * (attempt + 1))
    raise AssertionError("unreachable")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--config", default=str(ROOT / "config" / "config.yaml"))
    parser.add_argument("--out", default=str(ROOT / "artifacts" / "sample_qa.md"))
    parser.add_argument("--pace-s", type=float, default=7.0,
                        help="pause between questions; back-off unit on HTTP 429")
    args = parser.parse_args(argv)

    config = load_config(args.config)
    pipeline = AnswerPipeline.build(config=config, root=ROOT)
    if pipeline.generator is None or not pipeline.generator.available:
        print("no live provider configured; sample_qa.md must come from a real model",
              file=sys.stderr)
        return 2
    manifest = json.loads((ROOT / "artifacts" / "corpus_manifest.json").read_text("utf-8"))

    entries: list[str] = []
    for index, (label, question) in enumerate(SAMPLES, start=1):
        if index > 1:
            time.sleep(args.pace_s)
        response = _ask(pipeline, question, args.pace_s)
        shown_question, categories = redact(question)
        note = (f" *(PII value redacted in this file; detected: {', '.join(categories)})*"
                if categories else "")
        entries.append(
            f"## {index}. {label}\n\n"
            f"**Q:** {shown_question}{note}\n\n"
            f"Route: `{response.route}` · class: `{response.query_class}`\n\n"
            "**A (verbatim):**\n\n"
            + "\n".join(f"> {line}" if line else ">" for line in response.text.splitlines())
            + "\n"
        )
        print(f"[{index}/{len(SAMPLES)}] {response.route:<8} {response.query_class}")

    header = (
        "# Sample Q&A\n\n"
        "Generated by `python scripts/make_sample_qa.py` from live pipeline "
        "responses. Answers are verbatim, including the single citation and the "
        "`Last updated from sources:` stamp, both attached from chunk metadata. "
        "Do not edit by hand; regenerate.\n\n"
        f"| Field | Value |\n|---|---|\n"
        f"| Generated | {dt.datetime.now(dt.timezone.utc).isoformat(timespec='seconds')} |\n"
        f"| Model | `{config.generation.provider}` / `{config.generation.model}` |\n"
        f"| Corpus version | `{manifest.get('corpus_version', '')}` |\n"
        f"| Chunking | `{config.chunking.strategy}` |\n\n"
    )
    out = pathlib.Path(args.out)
    out.write_text(header + "\n".join(entries), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
